export const viaggi = [
  {
    id: 1,
    destinazione: "Tokyo, Giappone",
    durata: "10 giorni",
    prezzo: 1500,
    tipo: "Cultura e Tecnologia",
    partenza: "Oggi",
  },
  {
    id: 2,
    destinazione: "Roma, Italia",
    durata: "5 giorni",
    prezzo: 800,
    tipo: "Storia e Arte",
    partenza: "Domani",
  },
  {
    id: 3,
    destinazione: "New York, USA",
    durata: "7 giorni",
    prezzo: 2000,
    tipo: "Metropoli e Shopping",
    partenza: "Oggi",
  },
  {
    id: 4,
    destinazione: "Bali, Indonesia",
    durata: "12 giorni",
    prezzo: 1800,
    tipo: "Mare e Relax",
    partenza: "Domani",
  },
  {
    id: 5,
    destinazione: "Parigi, Francia",
    durata: "6 giorni",
    prezzo: 1200,
    tipo: "Romantico e Cultura",
    partenza: "Oggi",
  },
  {
    id: 6,
    destinazione: "Sydney, Australia",
    durata: "9 giorni",
    prezzo: 2200,
    tipo: "Avventura e Natura",
    partenza: "Domani",
  },
  {
    id: 7,
    destinazione: "Reykjavik, Islanda",
    durata: "8 giorni",
    prezzo: 1700,
    tipo: "Paesaggi e Avventura",
    partenza: "Oggi",
  },
  {
    id: 8,
    destinazione: "Bangkok, Thailandia",
    durata: "7 giorni",
    prezzo: 1300,
    tipo: "Esotico e Gastronomia",
    partenza: "Domani",
  },
];

export const contatti = [
  {
    id: 1,
    nome: "Luca",
    cognome: "Bianchi",
    citta: "Milano",
    sesso: "Maschio",
    viaggio_id: 1,
  },
  {
    id: 2,
    nome: "Giulia",
    cognome: "Rossi",
    citta: "Roma",
    sesso: "Femmina",
    viaggio_id: 1,
  },
  {
    id: 3,
    nome: "Marco",
    cognome: "Verdi",
    citta: "Napoli",
    sesso: "Maschio",
    viaggio_id: 1,
  },
  {
    id: 4,
    nome: "Elisa",
    cognome: "Ferrari",
    citta: "Torino",
    sesso: "Femmina",
    viaggio_id: 1,
  },
  {
    id: 5,
    nome: "Davide",
    cognome: "Moretti",
    citta: "Firenze",
    sesso: "Maschio",
    viaggio_id: 2,
  },
  {
    id: 6,
    nome: "Alessia",
    cognome: "Conti",
    citta: "Bologna",
    sesso: "Femmina",
    viaggio_id: 2,
  },
  {
    id: 7,
    nome: "Simone",
    cognome: "Galli",
    citta: "Genova",
    sesso: "Maschio",
    viaggio_id: 3,
  },
  {
    id: 8,
    nome: "Martina",
    cognome: "Ricci",
    citta: "Venezia",
    sesso: "Femmina",
    viaggio_id: 4,
  },
];
